[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "plotly>=6.0.0",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
